#pragma once

#include <string>
#include <SDL3/SDL.h>
#include <SDL3_image/SDL_image.h>
#include <SDL3_ttf/SDL_ttf.h>
#include <SDL3_mixer/SDL_mixer.h>
#include <cmath>
#include <format>

#include "Math.hpp"
#include "GlobalTypes.hpp"
#include "Sprite.hpp"
#include "Components/ComponentBase.hpp"
#include "GameObject.hpp"
#include "Camera/Camera.hpp"
#include "Scene.hpp"
#include "Window.hpp"
#include "GlobalLists.hpp"
#include "EssentialProcesses.hpp"
#include "HelperFunctions.hpp"
#include "InputKeys.hpp"
#include "Input.hpp"
#include "Rendering/Rendering.hpp"
#include "Rendering/SDLRenderer.hpp"
#include "Time.hpp"
#include "Framerate.hpp"
#include "UI/UIBase.hpp"
#include "Polygon.hpp"
