#pragma once

#include <iostream>
#include <algorithm>
#include <string>
#include <cctype>
#include <SDL3/SDL.h>
#include <SDL3_image/SDL_image.h>
#include <SDL3_ttf/SDL_ttf.h>
#include <SDL3_mixer/SDL_mixer.h>
#include <vector>
#include <random>
#include <unordered_map>
#include <filesystem>
#include <limits>
#include <cmath>
#include <format>
#include <memory>
#include <typeindex>

#include "Math.hpp"
#include "GlobalTypes.hpp"
#include "Sprite.hpp"
#include "Components.hpp"
#include "Gameobject.hpp"
#include "Camera.hpp"
#include "Scene.hpp"
#include "Window.hpp"
#include "GlobalLists.hpp"
#include "EssentialProcesses.hpp"
#include "HelperFunctions.hpp"
#include "InputKeys.hpp"
#include "Input.hpp"
